version: "3.9"
services:
  bsm-mysql:
    container_name: bsm-mysql
    image: mysql:8.0.33-debian
    cap_add:
      - SYS_NICE # CAP_SYS_NICE -> fix: mbind: Operation not permitted
    volumes:
      - ../mysql:/var/lib/mysql
      - ../sql:/docker-entrypoint-initdb.d
    restart: always
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=6G --group-concat-max-len=4294967295 --innodb_log_buffer_size=256M --innodb_write_io_threads=8 --innodb_flush_log_at_trx_commit=0 --innodb_doublewrite=0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bookstoremanagement
    ports:
      - 39062:3306
  # cache:
  #   container_name: cache
  #   image: redis:7.2-bookworm
  #   restart: always
  #   ports:
  #     - "63790:6379"
  #   command: redis-server --save 20 1 --loglevel warning --requirepass AvwQcUuAcmNymxrJxz3fCtcGFcc8U5xa
  bsm-be:
    image: golang:1.20.7-bookworm
    container_name: bsm-be
    volumes:
      - ../book-store-management-backend:/data
      - ./gin:/usr/bin/gin
    #  - $HOME/.aws:/root/.aws
    working_dir: /data
    environment:
      - GOMEMLIMIT=5120MiB
    entrypoint: "bash -c ./go-server.sh"
    ports:
      - 8080:8080
    depends_on:
      - bsm-mysql
      # - cache
    links:
      - bsm-mysql
      # - cache
  bsm-fe:
    image: lebaotriet/nodejs-18
    container_name: bsm-fe
    volumes:
      - ../book-store-management:/data
      - ../book-store-management/entrypoint.sh:/entrypoint.sh
      # - ../book-store-management/nginx.conf:/etc/nginx/sites-available/default
    ports:
      - 3000:3000
    working_dir: /data
    links:
      - bsm-be
    depends_on:
      - bsm-be
